/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

package PatientRecords;
import hospital.management.Dashboard;
import hospital.management.MainFrame;
import hospital.management.MyConnection;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;


public class MedicineAnalysisPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAnalysisPanel
     */
    private final MainFrame parent;
    private final Map<String, Integer> data = new LinkedHashMap<>();

    public MedicineAnalysisPanel(MainFrame parent) {
        initComponents();
        this.parent = parent;
        setPreferredSize(new java.awt.Dimension(700, 400));
        loadData();
        setOpaque(true);
        setBackground(Color.WHITE);

    }
    private void loadData() {
        try (Connection conn = MyConnection.getConnection()) {

            String sql = "SELECT medication, COUNT(*) AS count " +
                         "FROM visits GROUP BY medication";

            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                data.put(rs.getString("medication"), rs.getInt("count"));
            }

        } catch (Exception e) {
                        e.printStackTrace();

        }
    }
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);


        int baseLine = getHeight() - 50;
        int x = 50;
        int barWidth = 40;

        g.setColor(Color.BLUE);

        for (Map.Entry<String, Integer> entry : data.entrySet()) {

            int height = entry.getValue() * 30;

            g.fillRect(x, baseLine - height, barWidth, height);

            g.setColor(Color.BLACK);
            g.drawString(entry.getKey(), x, baseLine + 15);
            g.drawString(entry.getValue().toString(), x, baseLine - height - 5);

            g.setColor(Color.BLUE);
            x += 80;
        }
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(628, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(477, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        parent.showPanel(new Dashboard(parent));
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
