/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package PatientRecords;

import hospital.management.Dashboard;
import hospital.management.MainFrame;
import hospital.management.MainFrame;
import hospital.management.MyConnection;
import java.awt.Color;
import java.awt.Graphics;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author Rashi
 */
public class PatientProgressPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientProgressPanel
     */
    private final MainFrame parent;
     private ArrayList<String> months = new ArrayList<>();
private ArrayList<Integer> visitCounts = new ArrayList<>();
    private int patientId;
    public PatientProgressPanel(MainFrame parent, int patientId) {
        initComponents();
        this.parent = parent;
        this.patientId = patientId;
    loadMonthlyVisitData(patientId);
        setBackground(Color.WHITE);
    }
    
    private void loadMonthlyVisitData(int patientId) {

    months.clear();
    visitCounts.clear();

    try {
        String sql =
            "SELECT DATE_FORMAT(visit_date, '%Y-%m') AS visit_month, " +
            "COUNT(*) AS visit_count " +
            "FROM visits WHERE patient_id = ? " +
            "GROUP BY visit_month ORDER BY visit_month";

        PreparedStatement pst =
            MyConnection.getConnection().prepareStatement(sql);
        pst.setInt(1, patientId);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {
            months.add(rs.getString("visit_month"));
            visitCounts.add(rs.getInt("visit_count"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

@Override
protected void paintComponent(Graphics g) {
    super.paintComponent(g);

    if (months.isEmpty()) {
        g.drawString("No visit data available", 50, 50);
        return;
    }

    int startX = 80;
    int startY = getHeight() - 80;
    int xGap = 80;
    int yScale = 40;

    // Draw axes
    g.setColor(Color.BLACK);
    g.drawLine(startX, 40, startX, startY);                  // Y-axis
    g.drawLine(startX, startY, getWidth() - 40, startY);     // X-axis

    // Axis labels
    g.drawString("Month", getWidth() / 2 - 20, getHeight() - 30);
    g.drawString("Number of Visits", 10, getHeight() / 2);

    g.setColor(Color.BLUE);

    int prevX = startX;
    int prevY = startY;

    for (int i = 0; i < months.size(); i++) {

        int x = startX + (i * xGap);
        int y = startY - (visitCounts.get(i) * yScale);

        // Point
        g.fillOval(x - 4, y - 4, 8, 8);

        // Line
        if (i > 0) {
            g.drawLine(prevX, prevY, x, y);
        }

        // X-axis month labels
        g.setColor(Color.BLACK);
        g.drawString(months.get(i), x - 15, startY + 15);

        // Y-axis values
        g.drawString(
            String.valueOf(visitCounts.get(i)),
            startX - 30,
            y + 5
        );

        g.setColor(Color.BLUE);

        prevX = x;
        prevY = y;
    }
}



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("Back");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(634, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(418, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        parent.showPanel(new Dashboard(parent));
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
