/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visit;

import hospital.management.Dashboard;
import hospital.management.MainFrame;

/**
 *
 * @author Rashi
 */
public class VisitConsultation extends javax.swing.JPanel {

    /**
     * Creates new form VisitConsultation
     */
     private final MainFrame parent;

    public VisitConsultation(MainFrame parent) {
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3Add = new javax.swing.JButton();
        jButton4Update = new javax.swing.JButton();
        jButton5View = new javax.swing.JButton();
        jButton6Delete = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6Effect1 = new javax.swing.JButton();
        jButton4Update1 = new javax.swing.JButton();

        jPanel3.setBackground(new java.awt.Color(0, 45, 99));
        jPanel3.setToolTipText("");
        jPanel3.setPreferredSize(new java.awt.Dimension(700, 700));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Visit/ Consultation Data");

        jButton3Add.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3Add.setText("Add Visit");
        jButton3Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3AddMouseClicked(evt);
            }
        });
        jButton3Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3AddActionPerformed(evt);
            }
        });

        jButton4Update.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4Update.setText("Add Notes");
        jButton4Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4UpdateMouseClicked(evt);
            }
        });
        jButton4Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4UpdateActionPerformed(evt);
            }
        });

        jButton5View.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5View.setText("View All Visits");
        jButton5View.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5ViewMouseClicked(evt);
            }
        });
        jButton5View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ViewActionPerformed(evt);
            }
        });

        jButton6Delete.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6Delete.setText("Delete Visit");
        jButton6Delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6DeleteMouseClicked(evt);
            }
        });
        jButton6Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6DeleteActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton8.setText("Logout");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton9.setText("Back");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mr_1_50.png"))); // NOI18N

        jButton6Effect1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6Effect1.setText("Treatment Effectiveness Report");
        jButton6Effect1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6Effect1MouseClicked(evt);
            }
        });
        jButton6Effect1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6Effect1ActionPerformed(evt);
            }
        });

        jButton4Update1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4Update1.setText("Edit Visit");
        jButton4Update1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4Update1MouseClicked(evt);
            }
        });
        jButton4Update1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4Update1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3Add, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 252, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4Update1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5View, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(60, 60, 60))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6Effect1)
                .addGap(88, 88, 88)
                .addComponent(jButton8)
                .addGap(40, 40, 40))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(jButton4Update, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3Add)
                    .addComponent(jButton5View))
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6Delete)
                    .addComponent(jButton4Update1))
                .addGap(27, 27, 27)
                .addComponent(jButton4Update)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jButton8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jButton6Effect1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3AddMouseClicked
        // TODO add your handling code here:
        parent.showPanel(new AddVisit(parent));
        //        this.dispose();
    }//GEN-LAST:event_jButton3AddMouseClicked

    private void jButton3AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3AddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3AddActionPerformed

    private void jButton4UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4UpdateMouseClicked
        // TODO add your handling code here:
        parent.showPanel(new AddNotes(parent));
    }//GEN-LAST:event_jButton4UpdateMouseClicked

    private void jButton4UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4UpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4UpdateActionPerformed

    private void jButton5ViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5ViewMouseClicked
        // TODO add your handling code here:
        parent.showPanel(new ViewVisit(parent));
    }//GEN-LAST:event_jButton5ViewMouseClicked

    private void jButton5ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ViewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ViewActionPerformed

    private void jButton6DeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6DeleteMouseClicked
        // TODO add your handling code here:
        parent.showPanel(new DeleteVisit(parent));
    }//GEN-LAST:event_jButton6DeleteMouseClicked

    private void jButton6DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6DeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6DeleteActionPerformed

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        parent.showPanel(new Dashboard(parent));
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6Effect1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6Effect1MouseClicked
        // TODO add your handling code here:
        parent.showPanel(new TreatmentEffectivenessReport(parent));
    }//GEN-LAST:event_jButton6Effect1MouseClicked

    private void jButton6Effect1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6Effect1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6Effect1ActionPerformed

    private void jButton4Update1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4Update1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4Update1MouseClicked

    private void jButton4Update1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4Update1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4Update1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3Add;
    private javax.swing.JButton jButton4Update;
    private javax.swing.JButton jButton4Update1;
    private javax.swing.JButton jButton5View;
    private javax.swing.JButton jButton6Delete;
    private javax.swing.JButton jButton6Effect1;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
